environment = "Production"
vpc_cidrblock = "192.168.0.0/16"
countsub = 2
create_subnet = true
create_elastic_ip = true
desired_size = 2
max_size = 6
min_size = 2
instance_types = ["t2.medium"]
capacity_type = "ON_DEMAND"
ami_type = "AL2 x86_64"
label_one = "system:nodepool"
eks_version = "1.32"
domain-name = "dizzytech.online"
cluster_name = "eks-cluster"
repository_name = "eks-repository"
email = "desireoduma@outlook.com"
